## NUMPY
- 연산 속도가 매우 빠름
- vectorization: 하드웨어의 성능
- made with C
- nd array라는 데이터 구조를 잘 활용해 전문가들이 쓰기 편리
- 기초 library가 탑재되어있기 때문에 편의성

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.1'

In [4]:
# array
a = np.array([1,'1'])

In [5]:
a

array(['1', '1'], dtype='<U11')

In [6]:
type(a)

numpy.ndarray

In [7]:
# 인스턴스 방식으로
aa = np.array([[[1,2],[3,4]], [[1,2],[3,4]]])
aa # 내부적으론 list # 차원을 구분 

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [8]:
type(aa)

numpy.ndarray

In [9]:
aa.ndim # [[[ 갯수 

3

In [10]:
aa.size

8

In [12]:
aa.itemsize

4

In [11]:
aa.dtype

dtype('int32')

In [13]:
b = np.full((3,4),5)

In [14]:
b

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [21]:
b[...,0]

array([5, 5, 5])

In [23]:
...

Ellipsis

In [15]:
c = np.ones_like(b)

In [16]:
c

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [17]:
a = np.arange(25)

In [18]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
a = a.reshape(5,5)

In [20]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
class B(int):
    def __add__(self,other):
        print('add')
    pass

In [27]:
x = B(3)

In [28]:
x+x

add


In [30]:
a = [1,2,3]
b = [4,5,6]
a+b 

[1, 2, 3, 4, 5, 6]

In [31]:
# element-wise
x = np.array(a)
y = np.array(b)
x+y

array([5, 7, 9])

In [41]:
# bullin indexing
x[(x > 10) & (x < 5)]

masked_array(data=[],
             mask=[],
       fill_value=999999,
            dtype=int32)

In [39]:
x = np.ma.masked_array([1,2],[True,False]) # missing data 처리해주기 좋음

In [40]:
x

masked_array(data=[--, 2],
             mask=[ True, False],
       fill_value=999999)

In [43]:
d = [[1,2],[3,4]]

In [44]:
# dot product
np.dot(d,d)

array([[ 7, 10],
       [15, 22]])

In [46]:
a = np.arange(25).reshape(5,5)

In [47]:
a[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
a[0,1]

1

In [48]:
import seaborn as sns

In [50]:
tips = sns.load_dataset('tips')

In [51]:
tips[['sex','day']]

sex   day
0    Female   Sun
1      Male   Sun
2      Male   Sun
3      Male   Sun
4    Female   Sun
5      Male   Sun
6      Male   Sun
7      Male   Sun
8      Male   Sun
9      Male   Sun
10     Male   Sun
11   Female   Sun
12     Male   Sun
13     Male   Sun
14   Female   Sun
15     Male   Sun
16   Female   Sun
17     Male   Sun
18   Female   Sun
19     Male   Sat
20     Male   Sat
21   Female   Sat
22   Female   Sat
23     Male   Sat
24     Male   Sat
25     Male   Sat
26     Male   Sat
27     Male   Sat
28     Male   Sat
29   Female   Sat
..      ...   ...
214  Female   Sat
215  Female   Sat
216    Male   Sat
217    Male   Sat
218    Male   Sat
219  Female   Sat
220    Male   Fri
221  Female   Fri
222    Male   Fri
223  Female   Fri
224    Male   Fri
225  Female   Fri
226  Female   Fri
227    Male   Sat
228    Male   Sat
229  Female   Sat
230    Male   Sat
231    Male   Sat
232    Male   Sat
233    Male   Sat
234    Male   Sat
235    Male   Sat
236    Male   Sat
237    Male   Sat
238  Female   Sat
239    Male   Sat
240  Female   Sat
241    Male   Sat
242    Male   Sat
243  Female  Thur

[244 rows x 2 columns]

In [55]:
# 함께 mutable
a = b = [1,2,3]

In [53]:
a[0] = 100

In [54]:
b # 얘도 바뀜!

[100, 2, 3]

In [56]:
a = [[1,2],[3,4]]
b = a[:]

In [57]:
a[0][0] = 100

In [58]:
b

[[100, 2], [3, 4]]

In [59]:
# 안바뀌게 하려면
import copy

In [62]:
a = [[1,2],[3,4]] # fancy indexing
b = copy.deepcopy(a)

In [63]:
a[0][0] = 100

In [64]:
b

[[1, 2], [3, 4]]

In [65]:
# numpy는 기본적으로 deepcopy

In [67]:
x = np.array([[1,2],[3,4]])
y = x.copy() # 변동 없음!

In [69]:
y[0,0] = 100

In [70]:
x # 원본 백업용으로 좋다

array([[1, 2],
       [3, 4]])

In [71]:
y = x.view() # 변동되게 하려면 view

In [72]:
y[0,0] = 100
x

array([[100,   2],
       [  3,   4]])