In [5]:
# numpy 복습
import numpy as np
import seaborn as sns

In [2]:
mpg = sns.load_dataset('mpg')

In [3]:
mpg[['cylinders','origin']] # fancy indexing의 장점: 두개 다 불러올 수 있음

cylinders  origin
0            8     usa
1            8     usa
2            8     usa
3            8     usa
4            8     usa
5            8     usa
6            8     usa
7            8     usa
8            8     usa
9            8     usa
10           8     usa
11           8     usa
12           8     usa
13           8     usa
14           4   japan
15           6     usa
16           6     usa
17           6     usa
18           4   japan
19           4  europe
20           4  europe
21           4  europe
22           4  europe
23           4  europe
24           6     usa
25           8     usa
26           8     usa
27           8     usa
28           8     usa
29           4   japan
..         ...     ...
368          4     usa
369          4     usa
370          4     usa
371          4     usa
372          4     usa
373          4     usa
374          4     usa
375          4  europe
376          4   japan
377          4   japan
378          4     usa
379          4     usa
380          4   japan
381          4   japan
382          4   japan
383          4   japan
384          4   japan
385          4   japan
386          6     usa
387          6     usa
388          4     usa
389          6     usa
390          4   japan
391          4     usa
392          4     usa
393          4     usa
394          4  europe
395          4     usa
396          4     usa
397          4     usa

[398 rows x 2 columns]

In [13]:
a =  np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
# strides: Strides are the number of bytes to jump-over in the memory in order to get from one item to the next item
#         along each direction/dimension of the array. In other words, it's the byte-separation between consecutive 
#         items for each dimension.
a.strides # 얼마나 빨리 계산할 수 있냐? --- 4개씩!

(4,)

In [8]:
a.shape

(25,)

In [9]:
b = a.reshape(5,5)

In [10]:
b.strides # 한번 행이 넘어가려면 20만큼 데이터가 필요하고 열이 넘어가면 4만큼 필요하다.

(20, 4)

In [14]:
b.sum(axis=0, initial=1) # from functools import reduce 의 reduce와 같음

array([51, 56, 61, 66, 71])

In [15]:
np.add(3,4)

7

In [16]:
np.add([2,3,],[4,5]) # , 있어도 다 더해짐

array([6, 8])

In [17]:
np.sum(2)

2

In [18]:
# 우아한 scipy
# 중요!
import scipy

In [19]:
np.lookfor('sum') # sum이 들어간 모든 것들 찾아준다.

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.matrix.sum
    Returns the sum of the matrix elements, along the given axis.
numpy.logaddexp2
    Logarit

In [22]:
np.lookfor('*') # np에서 제공해주는 모든 애들

Search results for '*'
----------------------
numpy.i0
    Modified Bessel function of the first kind, order 0.
numpy.abs
    Calculate the absolute value element-wise.
numpy.add
    Add arguments element-wise.
numpy.cos
    Cosine element-wise.
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.gcd
    Returns the greatest common divisor of ``|x1|`` and ``|x2|``
numpy.lcm
    Returns the lowest common multiple of ``|x1|`` and ``|x2|``
numpy.log
    Natural logarithm, element-wise.
numpy.mod
    Return element-wise remainder of division.
numpy.sin
    Trigonometric sine, element-wise.
numpy.tan
    Compute tangent element-wise.
numpy.cbrt
    Return the cube-root of an array, element-wise.
numpy.ceil
    Return the ceiling of the input, element-wise.
numpy.conj
    Return the complex conjugate, element-wise.
numpy.cosh
    Hyperbolic cosine, element-wise.
numpy.exp2
    Calculate `2**p` for all `p` in the input array.
numpy.fabs
    Compute the absolute v

In [ ]:
# data type 에 따라 속도가 천차만별. np.float64가 가장 좋을 것

In [23]:
a = np.arange(1000, dtype = np.float64)

In [24]:
b = np.arange(1000)

In [25]:
c = np.arange(1000, dtype=np.float16)

In [26]:
%timeit a*a

1.13 µs ± 35.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [27]:
%timeit b*b

1.91 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
%timeit c*c

8 µs ± 634 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
np.sctypeDict # 단축어

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.intc,
 5: numpy.intc,
 'uint': numpy.uint32,
 'I': numpy.uintc,
 6: numpy.uintc,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.longdouble,
 'g': numpy.longdouble,
 13: numpy.longdouble,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64

In [30]:
a = np.array([1,2,3])

In [31]:
b = np.asfarray(a)

In [32]:
from sklearn.pipeline import Pipeline

In [33]:
from sklearn.ensemble import VotingClassifier

In [35]:
tips = sns.load_dataset('tips')

In [37]:
tips.sex[4] # 이것도 다 된다 

'Female'

In [39]:
a = np.arange(25)

In [42]:
a.reshape(5,5)[1,2]

7

In [51]:
a.reshape(5,5) # reshape해도

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
a # return이 잆다는 뜻 => a is immutable, thus no change!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [48]:
b = [1,2,3]

In [49]:
b.append(4)

In [50]:
b

[1, 2, 3, 4]

In [55]:
# sckit -> -1 넣으면 automation의 뜻. 자동으로 채워주는 것
a.reshape(5,-3) # 하지만 얜 뭐든 -값이면 automation 다 되게 만들어놓음

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
a.resize(5,6,refcheck=False) # 이럴땐? return 없다! 이 뜻은 a is mutable. refcheck=F 해놓아서 mutable이 됨!

In [57]:
a # 0으로 채움!

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24,  0,  0,  0,  0,  0]])

In [59]:
a.shape = (6,5) # 이렇게도 바꿀 수 있다

In [60]:
a 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  0,  0,  0,  0]])

In [61]:
from sklearn.model_selection import train_test_split

In [62]:
import inspect

In [63]:
print(inspect.getsource(train_test_split)) # 코드

def train_test_split(*arrays, **options):
    """Split arrays or matrices into random train and test subsets

    Quick utility that wraps input validation and
    ``next(ShuffleSplit().split(X, y))`` and application to input data
    into a single call for splitting (and optionally subsampling) data in a
    oneliner.

    Read more in the :ref:`User Guide <cross_validation>`.

    Parameters
    ----------
    *arrays : sequence of indexables with same length / shape[0]
        Allowed inputs are lists, numpy arrays, scipy-sparse
        matrices or pandas dataframes.

    test_size : float, int or None, optional (default=None)
        If float, should be between 0.0 and 1.0 and represent the proportion
        of the dataset to include in the test split. If int, represents the
        absolute number of test samples. If None, the value is set to the
        complement of the train size. If ``train_size`` is also None, it will
        be set to 0.25.

    train_size : float, int, or 

In [64]:
x = np.arange(25).reshape(5,5)
y = np.arange(24).reshape(4,6)

In [65]:
np.vsplit(y,2) # vertical

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [66]:
np.hsplit(y,2) # horizontal

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [67]:
np.vsplit(x,2) # 홀수는 등분이 안되니 안됨!

ValueError: array split does not result in an equal division

In [68]:
np.vsplit(x,(2,3)) # 구간을 나눠서 쪼갬. 2행 앞(0,1) 2~3행 중간(2) 3행 뒤(3,4)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [69]:
np.split(y,2) # axis = 0이기 때문에 vsplit과 같다.

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [74]:
np.split(y,2, axis =1) # axis = 1이기 때문에 hsplit과 같다.

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [75]:
a,b,c = np.vsplit(x,(2,3)) # unpacking

In [76]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
a,b = np.vsplit(y,2)

In [80]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [81]:
np.stack([a,b]) # 3차원으로 만들어버림 "join arrays along a new axis"

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [82]:
np.concatenate([a,b]) # 같은 차원! join arrays along existing axis

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [83]:
np.r_[a,b] # np의 row indexer

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [84]:
np.c_[a,b] # column indexer

array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]])