## Tensorflow

In [1]:
import tensorflow as tf
tf.debugging.set_log_device_placement(True)

In [4]:
a = 1

In [7]:
a = tf.constant([1,2,3]) # 상수만들기

In [8]:
a # tensorflow와 numpy는 100% 호환

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [10]:
a.numpy()

array([1, 2, 3])

In [9]:
type(a) # EagerTensor!

tensorflow.python.framework.ops.EagerTensor

In [14]:
a+a # 덧셈 됨

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6])>

In [15]:
import numpy as np
np.add(a,a) # 이제 완전 numpy

array([2, 4, 6])

In [16]:
# numpy -> tensor
c = np.array([1,2,3]) # 대신 메모리 많이 잡아먹음

In [17]:
tf.add(c,c)

Executing op Add in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6])>

In [11]:
b = tf.Variable([1,2,3]) # 변수만들기 할당된 값을 변화시킬 수 있음

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


In [12]:
b.assign_add([1,2,3])

Executing op AssignAddVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([2, 4, 6])>

In [13]:
b # b 자체가 바뀜

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 4, 6])>

In [19]:
np.add.reduce([1,2,3])

6

In [22]:
from tensorflow.keras.datasets import mnist

In [24]:
x, y = mnist.load_data() # len(mnist.load_data()) = 2 여서

In [25]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [27]:
X_train.shape, X_train.dtype

((60000, 28, 28), dtype('uint8'))

In [30]:
tf.data.Dataset.from_tensor_slices(X_train)

Executing op TensorSliceDataset in device /job:localhost/replica:0/task:0/device:CPU:0


<TensorSliceDataset shapes: (28, 28), types: tf.uint8>

In [31]:
s = tf.data.Dataset.from_tensor_slices(X_train)

Executing op TensorSliceDataset in device /job:localhost/replica:0/task:0/device:CPU:0


In [34]:
for i in s:
    print(i)
    break

Executing op OptimizeDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ModelDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AnonymousIteratorV2 in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op MakeIterator in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op IteratorGetNext in device /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor(
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0

In [ ]:
dir(s) # tf는 mutable, but for 돌리지 마라!!! 오래걸린다

In [32]:
ss = s.take(1) # 데이터 셋 한 개 뽑아줘

Executing op TakeDataset in device /job:localhost/replica:0/task:0/device:CPU:0


<TakeDataset shapes: (28, 28), types: tf.uint8>

# Keras 실전 예제
- https://www.tensorflow.org/tutorials/quickstart/beginner

In [38]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [ ]:
# 전처리
X_train, X_test = X_train / 255.0, X_test / 255.0 

In [45]:
model = tf.keras.models.Sequential # 단방향모델 -> multi input, multi output이 안됨. 상속해서 쓰는 정도로 쓰임.

Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0


In [46]:
model1 = tf.keras.models.Model 

In [47]:
issubclass(model, model1) # 상속해서 만듦

True

In [48]:
# https://keras.io/api/layers/core_layers/dense/
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(64, input_shape = (28,28)),  # Dense - fully connected layer
    tf.keras.layers.Dense(64),
    tf.keras.layers.Dense(10)
])

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalN

In [49]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 28, 64)            1856      
_________________________________________________________________
dense_1 (Dense)              (None, 28, 64)            4160      
_________________________________________________________________
dense_2 (Dense)              (None, 28, 10)            650       
Total params: 6,666
Trainable params: 6,666
Non-trainable params: 0
_________________________________________________________________


In [52]:
# flatten 시켜줘야 함
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),  # Flatten해서 전처리해주기
    tf.keras.layers.Dense(64),
    tf.keras.layers.Dense(10, name = 'output')
], name = 'moon')

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalN

In [61]:
model.summary()

Model: "moon"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_5 (Dense)              (None, 64)                50240     
_________________________________________________________________
output (Dense)               (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# http://playground.tensorflow.org/

In [ ]:
# python의 weight -> tensorflow의 kernel, tensorflow의 weight -> kernel + bias 

In [57]:
model.layers[1].weights

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


[<tf.Variable 'dense_5/kernel:0' shape=(784, 64) dtype=float32, numpy=
 array([[ 0.02903677,  0.05089132, -0.00398932, ...,  0.02807867,
         -0.07743905, -0.04619648],
        [ 0.02186813, -0.02057046, -0.0388759 , ..., -0.01652937,
          0.03463091,  0.01720702],
        [-0.00964707, -0.00479774, -0.04753993, ..., -0.02572171,
         -0.05972248, -0.00121913],
        ...,
        [-0.03348504, -0.03430975, -0.07271178, ..., -0.06369118,
          0.07786491, -0.04934387],
        [-0.05859987,  0.04932981,  0.04131133, ...,  0.06328212,
         -0.06153363, -0.02218421],
        [ 0.04686547,  0.06941067,  0.04556759, ..., -0.08322942,
         -0.02484574,  0.00715949]], dtype=float32)>,
 <tf.Variable 'dense_5/bias:0' shape=(64,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [ ]:
# keras에서 function loss 지정하기

In [ ]:
tf.keras.losses.  # tab 누르면 온갖 losses 나온다

In [62]:
model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhos

In [ ]:
model.fit(X_train, y_train, epochs=4)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op RangeDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op RepeatDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op MapDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op PrefetchDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op FlatMapDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op TensorDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op RepeatDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ZipDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ParallelMapDatasetV2 in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Ide

In [60]:
model.evaluate(X_test, y_test)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op RangeDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op RepeatDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op MapDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op PrefetchDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op FlatMapDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op TensorDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op RepeatDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ZipDataset in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ParallelMapDatasetV2 in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Ide

[2.327228546142578, 0.13249999284744263]

In [55]:
from sklearn.model_selection import cross_val_score

In [56]:
from sklearn.model_selection import KFold

In [ ]:
# cross_val_score(cv=KFlod(10))  # 비슷